### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by salehe-ee** [bytedance/MoMA#1]
Thank you for sharing your work. I'm interested in trying it out, however lots of dependencies seem to be missing from the `requirements.txt`.
Consider doing with version lock:
```
#!/bin/bash

pip freeze > requirements.txt
```

**Comment by salehe-ee** [comment]
After commit https://github.com/bytedance/MoMA/commit/bf8563e5d21a67a737bffc49c2826d28281bc798 I still get 
`ModuleNotFoundError: No module named 'llava'`

**Comment by KunpengSong** [comment]
Thanks for your interest !!

I just added a requirement_freeze.txt 
This could make it easier to install packages :)
